# Generated by Django 5.0.2 on 2024-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cure',
            name='book_location',
        ),
        migrations.AddField(
            model_name='cure',
            name='cure_location',
            field=models.TextField(default='00000000'),
        ),
    ]
