# Generated by Django 5.0.2 on 2024-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0003_cure_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cure',
            name='cure_location',
            field=models.TextField(default='On the shelf'),
        ),
    ]
